[2022-05-03 20:26:04,781] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: xcom_dag.choose_best_model 2022-05-03T20:25:52.349452+00:00 [queued]>
[2022-05-03 20:26:04,796] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: xcom_dag.choose_best_model 2022-05-03T20:25:52.349452+00:00 [queued]>
[2022-05-03 20:26:04,800] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-05-03 20:26:04,800] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-05-03 20:26:04,800] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-05-03 20:26:04,825] {taskinstance.py:1087} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-05-03T20:25:52.349452+00:00
[2022-05-03 20:26:04,829] {standard_task_runner.py:52} INFO - Started process 126478 to run task
[2022-05-03 20:26:04,838] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'xcom_dag', 'choose_best_model', '2022-05-03T20:25:52.349452+00:00', '--job-id', '85', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmp807cl_bm', '--error-file', '/tmp/tmpbe7jvc38']
[2022-05-03 20:26:04,844] {standard_task_runner.py:77} INFO - Job 85: Subtask choose_best_model
[2022-05-03 20:26:05,056] {logging_mixin.py:104} INFO - Running <TaskInstance: xcom_dag.choose_best_model 2022-05-03T20:25:52.349452+00:00 [running]> on host airflowvm
[2022-05-03 20:26:05,195] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-05-03T20:25:52.349452+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-03T20:25:52.349452+00:00
[2022-05-03 20:26:05,196] {logging_mixin.py:104} INFO - choose best model
[2022-05-03 20:26:05,207] {python.py:151} INFO - Done. Returned value was: <Task(DummyOperator): inaccurate>
[2022-05-03 20:26:05,207] {skipmixin.py:124} INFO - Following branch <Task(DummyOperator): inaccurate>
[2022-05-03 20:26:05,207] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/python.py", line 180, in execute
    self.skip_all_except(context['ti'], branch)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 128, in skip_all_except
    branch_task_ids = set(branch_task_ids)
TypeError: 'DummyOperator' object is not iterable
[2022-05-03 20:26:05,210] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=choose_best_model, execution_date=20220503T202552, start_date=20220503T202604, end_date=20220503T202605
[2022-05-03 20:26:05,257] {local_task_job.py:151} INFO - Task exited with return code 1
